import { ImageResult, MODEL_LABELS } from "@/types/webhook";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, Download, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";

interface ImageGalleryProps {
  results: ImageResult[];
  isLoading: boolean;
  selectedModels: string[];
}

export function ImageGallery({
  results,
  isLoading,
  selectedModels,
}: ImageGalleryProps) {
  const { toast } = useToast();

  const handleCopy = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard",
      description: `${label} has been copied`,
    });
  };

  const handleDownload = (url: string, model: string) => {
    const link = document.createElement("a");
    link.href = url;
    link.download = `${model}-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!isLoading && results.length === 0) {
    return null;
  }

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold">Generated Images</h2>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {selectedModels.map((model) => {
          const result = results.find((r) => r.model === model);

          return (
            <Card key={model} className="overflow-hidden">
              <CardHeader className="pb-4">
                <CardTitle className="flex items-center justify-between">
                  {MODEL_LABELS[model as keyof typeof MODEL_LABELS]}
                  {result && (
                    <Badge variant="secondary">Seed: {result.seed}</Badge>
                  )}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="aspect-video bg-muted rounded-lg overflow-hidden flex items-center justify-center">
                  {isLoading && !result ? (
                    <div className="flex flex-col items-center gap-3 text-muted-foreground">
                      <Loader2 className="h-8 w-8 animate-spin" />
                      <p className="text-sm">Generating...</p>
                    </div>
                  ) : result ? (
                    <img
                      src={result.image_url}
                      alt={`Generated by ${MODEL_LABELS[model as keyof typeof MODEL_LABELS]}`}
                      className="w-full h-full object-cover"
                    />
                  ) : null}
                </div>

                {result && (
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <p className="text-xs font-medium text-muted-foreground">
                        Final Prompt
                      </p>
                      <p className="text-sm bg-muted p-2 rounded border border-border">
                        {result.prompt_used}
                      </p>
                    </div>

                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() =>
                          handleCopy(result.prompt_used, "Prompt")
                        }
                        className="flex-1"
                      >
                        <Copy className="h-4 w-4 mr-1" />
                        Copy
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() =>
                          handleDownload(result.image_url, result.model)
                        }
                        className="flex-1"
                      >
                        <Download className="h-4 w-4 mr-1" />
                        Download
                      </Button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
